### PR TITLE
feat: return `purchaseStatus` in `.purchase()`

### PR DESCRIPTION
**Pull request by tomasstark**
This PR returns a new `purchaseStatus` property  when calling `.purchase()`. This property is needed
for the integrating apps to better handle the last item on tab scenario.

### CODE REVIEW

**Review by jmcodingde — CHANGES_REQUESTED** [review]
The change in the method `purchase` LGTM 👍

I think the tests need to be updated to reflect this.

**Comment by tomasstark** [comment]
@jmcodingde Sorry, this was not ready for a review. I mistakenly created this PR via GH CLI without draft state. But thank you for a review 😂

**Comment by jmcodingde** [comment]
@tomasstark Np, I appreciate the progress 🚀

Lmk when it's ready for review.

**Comment by tomasstark** [comment]
@jmcodingde Ok, this is now ready. The issues with tests were not because of `purchaseStatus` property but rather because we updated `@getsupertab/tapper-sdk` from 3.0.0 to 9.0.0. Between these versions, there were updates to the OpenAPI schema that made our generator for tapper-sdk make all properties required (yet nullable) and we didn't reflect this in the types here, particularly `ClientConfig` type.

**Review by jmcodingde — APPROVED** [review]
LGTM 👍

**Pull request merged**
